version: '2.1'

services:
  location-service:
#    build: .
    image: atyron/location-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=location
    depends_on:
      kafka:
        condition: service_healthy
    links:
      - kafka

  elasticsearch:
    image: elasticsearch:5.2.2
    ports:
      - "9200:9200"
    environment:
      - "xpack.security.enabled=false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - /mnt/data/location-esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:5.2.2
    ports:
      - "5601:5601"
    environment:
      - "xpack.security.enabled=false"
    depends_on:
      elasticsearch:
        condition: service_healthy

  logstash:
    image: logstash:5.2.2
    ports:
      - "25826:25826"
    volumes:
      - ./elk-config:/elk-config
    command: logstash -f /elk-config/logstash.config
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=location
      - ELASTIC_HOST=elasticsearch
    links:
      - kafka
      - elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Maintains configuration information for kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
#      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "location:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "bash", "-c", "unset" , "JMX_PORT" ,";" ,"kafka-topics.sh","--zookeeper","zookeeper:2181","--list"]
      interval: 10s
      timeout: 5s
      retries: 10